Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-062df10d14676e201
      InstanceType: t2.micro
      KeyName: test-key
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt-get update -y
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt install apache2 -y
            sudo apt install ansible -y
            
            wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
            echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
            sudo apt-get update
            sudo apt-get install grafana -y
            sudo systemctl start grafana-server
            sudo systemctl status grafana-server
            sudo systemctl enable grafana-server.service


            export RELEASE="2.2.1"
            # 1. Creating Prometheus System Users and Directory
            sudo useradd --no-create-home --shell /bin/false prometheus
            sudo useradd --no-create-home --shell /bin/false node_exporter
            sudo mkdir /etc/prometheus
            sudo mkdir /var/lib/prometheus

            # 2. Update Prometheus user
            sudo chown prometheus:prometheus /etc/prometheus
            sudo chown prometheus:prometheus /var/lib/prometheus
            cd /opt/
            wget https://github.com/prometheus/prometheus/releases/download/v2.26.0/prometheus-2.26.0.linux-amd64.tar.gz

            # 4.Install Prometheus and Grafana on Ubuntu 20.04 LTS
            sha256sum prometheus-2.26.0.linux-amd64.tar.gz
            tar -xvf prometheus-2.26.0.linux-amd64.tar.gz
            cd prometheus-2.26.0.linux-amd64

            # 5. Copy Prometheus Binary files
            sudo cp /opt/prometheus-2.26.0.linux-amd64/prometheus /usr/local/bin/
            sudo cp /opt/prometheus-2.26.0.linux-amd64/promtool /usr/local/bin/

            # 6. Update Prometheus user ownership on Binaries
            sudo chown prometheus:prometheus /usr/local/bin/prometheus
            sudo chown prometheus:prometheus /usr/local/bin/promtool

            # 7. Copy Prometheus Console Libraries
            sudo cp -r /opt/prometheus-2.26.0.linux-amd64/consoles /etc/prometheus
            sudo cp -r /opt/prometheus-2.26.0.linux-amd64/console_libraries /etc/prometheus
            sudo cp -r /opt/prometheus-2.26.0.linux-amd64/prometheus.yml /etc/prometheus

            # 8. Update Prometheus ownership on Directories
            sudo chown -R prometheus:prometheus /etc/prometheus/consoles
            sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
            sudo chown -R prometheus:prometheus /etc/prometheus/prometheus.yml

            # 10. Prometheus configuration file
            cat /etc/prometheus/prometheus.yml

            # 11. Creating Prometheus Systemd file
            sudo -u prometheus /usr/local/bin/prometheus \
              --config.file /etc/prometheus/prometheus.yml \
              --storage.tsdb.path /var/lib/prometheus/ \
              --web.console.templates=/etc/prometheus/consoles \
              --web.console.libraries=/etc/prometheus/console_libraries
            exit
            sudo touch /etc/systemd/system/prometheus.service
            echo "[Unit]
                  Description=Prometheus
                  Wants=network-online.target
                  After=network-online.target
                  [Service]
                  User=prometheus
                  Group=prometheus
                  Type=simple
                  ExecStart=/usr/local/bin/prometheus \
                      --config.file /etc/prometheus/prometheus.yml \
                      --storage.tsdb.path /var/lib/prometheus/ \
                      --web.console.templates=/etc/prometheus/consoles \
                      --web.console.libraries=/etc/prometheus/console_libraries
                      --web.listen-address=0.0.0.0:9090
                  Restart=always
                  RestartSec=10s
                  [Install]
                  WantedBy=multi-user.target
                  " > /etc/systemd/system/prometheus.service

            sudo systemctl daemon-reload
            sudo systemctl start prometheus
            sudo systemctl enable prometheus
            sudo systemctl status prometheus


      Tags:
        - Key: Name
          Value: Prometheus-Grafana-OS 

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SG to allow SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '9090'
          ToPort: '9090'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '9100'
          ToPort: '9100'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: SSH-SG